name: Android Build

on: pull_request

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest

  steps:



    steps:

      - name: Set Up JDK
        uses: actions/checkout@v2
        with:
          java-version: 1.8

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

